apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-data-pv
  labels:
    app: backend-data
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /backend-data
    type: DirectoryOrCreate
