PasswordAuthentication no
PubkeyAuthentication yes

PermitRootLogin no

MaxAuthTries 3
LoginGraceTime 30

X11Forwarding no
AllowTcpForwarding no
AllowStreamLocalForwarding no
GatewayPorts no

ClientAliveInterval 300
ClientAliveCountMax 2

MaxStartups 10:30:100

DebianBanner no

Match User ubuntu
    # Allow SSH tunneling for the ubuntu user
    AllowTcpForwarding yes