apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-strapi-pv
  labels:
    app: postgres-strapi
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard 
  persistentVolumeReclaimPolicy: Retain 
  hostPath: 
    path: /postgres-strapi-data
    type: DirectoryOrCreate
