apiVersion: apps/v1
kind: Deployment
metadata:
  name: tor-daemon
  namespace: envoy-gateway-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tor-daemon
  template:
    metadata:
      labels:
        app: tor-daemon
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault

      containers:
        - name: tor
          image: dockurr/tor:0.4.9.11@sha256:446881b3366cbc2cc5cf8d13a76e3104f60824b7c15343d14defe903ded18f0d
          volumeMounts:
            - name: tor-config
              mountPath: /etc/tor
            - name: tor-data
              mountPath: /var/lib/tor
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"

      volumes:
        - name: tor-config
          configMap:
            name: tor-config
        - name: tor-data
          persistentVolumeClaim:
            claimName: tor-hostname-data
