apiVersion: v1
kind: Service
metadata:
  name: portfolio-frontend-service
  namespace: portfolio
spec:
  selector:
    app: portfolio-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
