apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-sonarqube-pvc
  namespace: sonarqube
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-path
