apiVersion: v1
kind: Service
metadata:
  name: redirection-service
  namespace: portfolio
spec:
  selector:
    app: redirection
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redirection-deployment
  namespace: portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redirection
  template:
    metadata:
      labels:
        app: redirection
    spec:
      containers:
        - name: nginx
          image: yaniskouidri/kouidri-redirection-arm
          ports:
            - containerPort: 80

