apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: immich-server-policy
  namespace: immich
spec:
  podSelector:
    matchLabels:
      app: immich-server
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: envoy-gateway-system
      ports:
        - protocol: TCP
          port: 2283
  egress:
    # PostgreSQL
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: immich
          podSelector:
            matchLabels:
              app: immich-db
      ports:
        - protocol: TCP
          port: 5432

    # Redis
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: immich
          podSelector:
            matchLabels:
              app: redis
      ports:
        - protocol: TCP
          port: 6379

    # Machine Learning
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: immich
          podSelector:
            matchLabels:
              app: machine-learning-server
      ports:
        - protocol: TCP
          port: 3003

    # HTTPS Internet
    - ports:
        - protocol: TCP
          port: 443