# To add/set/remove headers to all HTTPS response/request
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: global-response-header-policy
  namespace: envoy-gateway-system
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: envoy-gateway
    sectionName: https
  headers:
    lateResponseHeaders:
      set:
        - name: Strict-Transport-Security
          value: max-age=31536000; includeSubDomains; preload
        - name: X-Content-Type-Options
          value: nosniff
        - name: X-Frame-Options
          value: DENY
        - name: Referrer-Policy
          value: no-referrer
        - name: Permissions-Policy
          value: geolocation=(), microphone=(), camera=()
        - name: Cross-Origin-Opener-Policy
          value: same-origin
        - name: Cross-Origin-Embedder-Policy
          value: require-corp
        - name: Cross-Origin-Resource-Policy
          value: same-origin
      remove:
        - server # Do not reveal server information (nginx, envoy, etc.)
        - x-powered-by # Do not reveal server information (Express, PHP, etc.)
  tls:
    session:
      resumption:
        stateless: {}
