# To add/set/remove headers to all HTTPS response/request
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: global-response-header-policy
  namespace: envoy-gateway-system
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: envoy-gateway
    sectionName: https
  headers:
    lateResponseHeaders:
      set:
        - name: Strict-Transport-Security
          value: max-age=31536000; includeSubDomains; preload
  tls:
    session:
      resumption:
        stateless: {}
