apiVersion: ENC[AES256_GCM,data:bh4=,iv:McyPCO5Mw9CRogZxbU20Yh/Dt7fKGVykkh2bXmU5w54=,tag:MgXnSXwpdpEjxSfVAPvLWA==,type:str]
kind: ENC[AES256_GCM,data:4Y08LcrS,iv:Na/+V3dw/mkQaBzPmG35Y1ebEWXdYwrqPxRDe4pPwAE=,tag:r0IN7B+vVWWEsun9o59pWA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:GnkHZyAnXQ==,iv:j2rv594kuGJvcmodFo1hyMweKw31w76/6LF347H8fHg=,tag:jTn8UKnl+EeQSI74tbUsTw==,type:str]
    namespace: ENC[AES256_GCM,data:OxPanqNUgXHU,iv:hrKnjBZ1pBmbOTiQey+CTaxCjySzSF3yVYb3zSijCBk=,tag:fadxZyyUyeh+kUUPzOnUWA==,type:str]
type: ENC[AES256_GCM,data:dFwN6tWc,iv:9X36Lc4h2ef5yyNKTJjks2DpD5J8BMgaTjwBxv3ZT0U=,tag:ArIRocVzzmWQFch7R222/Q==,type:str]
stringData:
    MONGODB_URI: ENC[AES256_GCM,data:DlvE2HWUvr5y/YtbjBrD/7qhk2MlLc5le0qFDeFbme0vEo98nqW6GttEWmuQ8GtDlNy+1VHX7lsWGYORk5MyzTadfHgzYDlGZkxZnEDvr5gSd7fKuuLZESWYkHqqwmFIvGesYlpQfsE=,iv:vCmPXwY0Ee6XHGoMyTdzcWGXKebtuvjdkQG+q4Le1hw=,tag:eC8ScpmZc18gbdVGCE6yqg==,type:str]
    SIGNUP_KEY: ENC[AES256_GCM,data:Ov9/5R/W1E9+Lh0XiildBp7/loLG/lEFZ8t8OqE1u0fDVW1+gng=,iv:eUbNMBovzyQlT3sHA+NfcA5pamkI9Hs0Hx13RSrN6+E=,tag:XLgrYJcByZ6e+TrVdVDz8g==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:o0+Fj2vZyPpxA/ZpKTYTNzaPW/88VxjblNLpHMTJ3lbI/TyR1Arb7KvPUia7MacjlbLxZBVK9ojJz2WN1Jl2dQ==,iv:K9o/HvOTyC5g6Cd6UFU0/CfUu5goyP+WeYtpI4UlzUs=,tag:A8+JaWx979k9a5Y3CKa5/g==,type:str]
sops:
    age:
        - recipient: age1kyhazfmr49eddkxfws9apdlauaevqsktfhfhyxdhkxhwdg03qszs7c337j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGdFpKL2tBQ2kzNW9GSWxi
            K3l3WkUrdjlxT09BL3VwNWcxZWFjcGVzQzMwCk10bWIwRUlkVVBTaWxSRk1EUSt2
            K1h5RTFaSVNnQXJwV1ZVS2tOSTVqdlkKLS0tIEp3VzN0dkdpbE4xM3VEaFk1czdT
            UHdqZkFtSlFvQ3NWeFExRzB4U2NwRUUKpWok/13VazQV1/Kx24tsbyscgKcwwvuH
            GeuM1hvYuIVwWC5v5X60hK6PCYsQLb0MAj917WJbvf7o9Dj+BmjqmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T10:03:53Z"
    mac: ENC[AES256_GCM,data:PAxGiKF6UDbw/0vKiDb5W1XCJcMFRFe64agDVlXwhAn+C9bNkXTH61CGohNE5FFziAA8yVEm2RGBlKiGcLrv/dgPbeWvDQMXM7nWRg82oXr20RsnzWNeW55dkLoeKfdzHBYUb48RZectnhFMPEryUZWrLXF++CroHU+zyzxss2M=,iv:07xqMHx9mfTpb4cgrqGmAWlwnBB7/JpPc0cBZEZ0FmU=,tag:9qIwCCT08NkSHYSasniwzw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
