apiVersion: v1
kind: Secret
metadata:
    name: n8n-secret
    namespace: n8n
type: Opaque
stringData:
    #ENC[AES256_GCM,data:gB92ZEnm/NHWjoMNnU+5psC3TyETmXK1JcKm/eHkUD8F4LZV/W68CgR4MIsqn8ZGyrPGrMP+AFnTRMekZS8nEvX1fGD/tvQ=,iv:1GwbG+hYvTDrmzq0gEWQ67l6d9RbdY0oIxMLkyJvBRo=,tag:tNJJ+qjCDgAhZfM2V/gw0w==,type:comment]
    #ENC[AES256_GCM,data:l4qT89IowjoydNjYsMTf4LRCbJabD8BaVzTZIa+67etbnMC0hcc6aDbYIN4YSq7USIfZg14dpNsE3Dd7CaGiPyCcofw72g4iFQyv,iv:afQNZxgboWqABJxu9rhSUayJYEwghmsXHgP/OEGdamY=,tag:4uSXwixm4kTuGf403BcLdA==,type:comment]
    #ENC[AES256_GCM,data:6fRdtH8prAMr12V2vst6pA5wij/6yHAAGvd3qZkGdTJ2o5yEd0msUpRYimm1iYDZZGMx,iv:BY3BTyYotkkB58TVwmxrB/fpArkZ3KKXNKcz9qLtIco=,tag:stEQtnX72lSzeIVPRBWCvA==,type:comment]
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:LuyVE28Dk2Of1oU1d4nnvTXZEtBc+Wk6o7ftbrYY0c4=,iv:9cO7dOqB1abJ+iB55j51co+qx+FHfmmU0HRDFTQrv6k=,tag:dbG9HHDMaPn7vai0FVr4JQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhM255STdET0hLSjJpT1NF
            WXgyTzE2MW5oeit3eEhPVFdxYzltbUIrclcwClVGV2MxVXkwd3d4ZjJ0alFwU2lP
            c1JxbVFqdjNWbnRONUNoUkI1UFJrcDQKLS0tIFpBV2lTaE9kL0lTcnZJK2FvRkpQ
            OCtDb2NKUzk4M0FtcmZIN1JuNHM5K00KTg/Ev50tgpsPo2vxedouJAj2lKCFz+rd
            7crHuiL/JbFmhU8PJIdtePugCALeAmE+2L0QXsjIjHAnXp/AKf/55A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kyhazfmr49eddkxfws9apdlauaevqsktfhfhyxdhkxhwdg03qszs7c337j
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T20:23:49Z"
    mac: ENC[AES256_GCM,data:4DGM+uwJvgWq7TSICRSQ/GEN/IIMsz9ucfI6KBWDzWBLooKwTVNHQGBSej1/q1rZZMUbLnFk3UtO0pPVJQU7V6xwwTzT4SkcU2fPVhPqUnU9UszYw+6Kj6ZgTE+hehY1jaev24oA1Z8D/AcVP3GTz0Hv+iVHKsdrmlKjIXGOKIU=,iv:KDcIgJmmpU4uWXIZSRzS/voRKb/FqnAZAv+VYhSmTzg=,tag:V6E461Xiz3lccNZn0kJcwg==,type:str]
    version: 3.13.2
