apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: n8n
spec:
  podSelector: {}  # all namespace pods are selected
  policyTypes:
    - Ingress
    - Egress