apiVersion: v1
kind: Secret
metadata:
    namespace: n8n
    name: postgres-secret
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:uFlnwYXlF7M=,iv:4b4MVItC6pWRiHxd+1pdpNbvoa7d20c7zgT372kNAj8=,tag:hgO/CIAi7BzOxWfPoXyShw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:PaG0wgZLv8FPi7LidV9bWnpkStz8LT/fQUuVF087pKI/UhMvMYyhBcDge9y+mDPpThGcBGq3WP45SFfTkXE1cw==,iv:E90ZyDczG1jNDhh6PESlbV7xhqCQhv5n60JFcn2O+a8=,tag:TNKTOL9CLn5xRaS0YuI/Vg==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:sgMT,iv:5vaghsD2gZuM/BpSsX6hqZIEhrXmRtCWbvD3R1ntLf8=,tag:7v07jadFbFQFXmXbMrW0XA==,type:str]
    POSTGRES_NON_ROOT_USER: ENC[AES256_GCM,data:9zJF,iv:5UvBDoCECzEVkyEyrei2Ishh6y2tbLSMWx4a/qIWYao=,tag:P9gspcW5jGAKhN+ivqTDrA==,type:str]
    POSTGRES_NON_ROOT_PASSWORD: ENC[AES256_GCM,data:9ptoXmJVDMbZKpvq9mGZLzEz8Nb6Dv91yJ4cfUpSMfwrbHwo5KhEPl+u8nQfKphr20FNszGZjbtu9LaWe5Ukiw==,iv:g4uKjfPEOD4EYLN7LrCzGnjdvSKsv3/HTJXdd6w4AQA=,tag:cmawjCVVrOnijSJBnDLlew==,type:str]
sops:
    age:
        - recipient: age1kyhazfmr49eddkxfws9apdlauaevqsktfhfhyxdhkxhwdg03qszs7c337j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3S2FtUFVZS0t0YzQ4dUhl
            NTViNnBPdVJ4UHhlSjY0N3F2cGMrSUMrQ0ZnCmVSUFBBQnZ4eTEyWlZ2TGtnWjJr
            ajNOTEVWUzdyMk9KalhSMHB4VW9VWEkKLS0tIFRHT1dzNFRIUmdXN01Bdjlmd3h1
            ZU1mWkFQNzhoVm1pbGdpbWc5YUp6N1EKmCrKoEYcEcpTMvlJ2YO4hvniXQSOHeup
            YfrdsDoLYDTchzdt3VcRWYcxzNsUBeiUCqjY2Pvc3335ocXYak9jbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-11T17:10:50Z"
    mac: ENC[AES256_GCM,data:o4xuPRDXgXV5d2o8A1kOkN4cM9w+GyhSHuMyl5xUFKSxwpYijJqMPoFOyBfnfjWJtAdTZW1gVbGm6Re0kb5tDdCEQhpcnsBYcnfMgc3QyNe2knriIg/dNu6fPD/NVHTo834Lb0BAMhxVOYWHzQPd0uGNBGtQ8t/rjcBng4D+SCU=,iv:+KhEIod1tx9EHHUuRMkpBgIgcxIBrsF+HdnTvcYv95A=,tag:MyPLCan31cp1gQKMQqaPkw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
