apiVersion: v1
kind: Secret
metadata:
    name: crowdsec-secret
    namespace: crowdsec
type: Opaque
stringData:
    ENROLL_KEY: ENC[AES256_GCM,data:7/hF8UU46lqqtq5jeN5BQ6zR01ojtaOHHw==,iv:Je1Zsnh+WBpx1zo7VAw/yh7p7yKkcFLi6Fdtsc9kwK8=,tag:a5DkZAqP2hFq8LDaO739iA==,type:str]
    ENROLL_INSTANCE_NAME: ENC[AES256_GCM,data:8hpMfig/ZDA/uVYyxXtt,iv:Rr10RDo/SMyus9soPB7AYnlMYcPatEQ0sgJdZ+ruiKc=,tag:X0si6uOsL9cj/gobMo+iIg==,type:str]
    ENROLL_TAGS: ENC[AES256_GCM,data:BQ1ZKHhrGEMkkb0W/d/gj5E=,iv:h4onF3KLJceUOiIGu/p4i408BFrhSLXH9+9qxD0mEqg=,tag:CbMYCJFHL6dtZgtDNdc2IQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1ZVVEMmZRcUxoWkxURTBs
            UWVjak9VOGdYVklndEtDVzVvMjZhMXdPVUVrCkpCc3E3UkR3S1owTXdObVJobVZO
            WVFMOEdTb0hzUVExaGRwU0JEQnlneE0KLS0tIFhpTVplWk9DYWVjTWxMeVkyRmpD
            NGhFNytmUEdXOHpuT1R2a3Q5ZjM2cncK6i5oFnIkDwNmFLvemze4l8Ucz8DF+QdX
            IBGkcXvn5EOtl9cFV9Bzg/bPEn8p9yzfJzcEebWm0hxbDT91ruqzHA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kyhazfmr49eddkxfws9apdlauaevqsktfhfhyxdhkxhwdg03qszs7c337j
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-18T16:07:54Z"
    mac: ENC[AES256_GCM,data:FiW3H9s43fa3oLmWppour86BM3J3S/H1WNZ50G6jqRXP2X2vt7+Tf44PnKYuoXoJ/2+MCwhVMgutZ8pHs8J2k1R5Fle8AS4WCOaljysv5HtupjjB8UAbXUBAit4ay1ITliX34BwzQbvvimKXJe6IjPWV7zjvBo+E+p2t4F+NwMA=,iv:1GerVyzPVO6GKQgCz1l90Ogm+3xw78X7WWcoSt7Sxhs=,tag:w3j6xLg/GKnX5IPBPIztOg==,type:str]
    version: 3.13.2
