# for raw logs format: json or cri (docker|containerd)
container_runtime: containerd

# Agent environment variables (to avoid duplication with chart defaults)
DISABLE_LOCAL_API: "true"
DISABLE_ONLINE_API: "false"
CROWDSEC_BYPASS_DB_VOLUME_CHECK: "true"
LOCAL_API_URL: "http://crowdsec-service.crowdsec:8080"
COLLECTIONS: "yanis-kouidri/envoy crowdsecurity/base-http-scenarios crowdsecurity/http-cve crowdsecurity/http-dos crowdsecurity/whitelist-good-actors crowdsecurity/linux"
PARSERS: "crowdsecurity/cri-logs"

agent:
  acquisition:
    # The namespace where the pod is located
    - namespace: envoy-gateway-system
      # The pod name
      podName: envoy-envoy-gateway-system-envoy-gateway-*
      # as in crowdsec configuration, we need to specify the program name to find a matching parser
      program: envoy
      poll_without_inotify: true
  additionalAcquisition:
    - source: file
      filenames:
        - /var/log/auth.log
      labels:
        type: syslog

lapi:
  envFrom:
    - secretRef:
        name: crowdsec-secret
