# for raw logs format: json or cri (docker|containerd)
container_runtime: containerd
agent:
  # Enable alert forwarding to CrowdSec Central API
  disableOnlineApi: false
  # Uncomment and set your CrowdSec API key to enable alert forwarding to Central API
  # onlineApi:
  #   key: "your-api-key-here"
  # Specify each pod whose logs you want to process
  acquisition:
    # The namespace where the pod is located
    - namespace: envoy-gateway-system
      # The pod name
      podName: envoy-envoy-gateway-system-envoy-gateway-*
      # as in crowdsec configuration, we need to specify the program name to find a matching parser
      program: envoy
      poll_without_inotify: true
  additionalAcquisition:
    - source: file
      filenames:
        - /var/log/auth.log
      labels:
        type: syslog
  env:
    - name: COLLECTIONS
      value: "yanis-kouidri/envoy crowdsecurity/base-http-scenarios crowdsecurity/http-cve crowdsecurity/http-dos crowdsecurity/whitelist-good-actors crowdsecurity/linux"
    - name: PARSERS
      value: "crowdsecurity/cri-logs"
lapi:
  envFrom:
    - secretRef:
        name: crowdsec-secret
