apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authentik
resources:
  - namespace.yaml
  - helm-repository.yaml
  - secrets.enc.yaml
  - helm-release.yaml
  - http-route.yaml
  # Network policies
  - network-policies/network-policy-default-deny.yaml
  - network-policies/network-policy-allow-dns.yaml
  - network-policies/network-policy-authentik-server.yaml
  - network-policies/network-policy-authentik-worker.yaml

configMapGenerator:
  - name: authentik-values
    files:
      - values.yaml

generatorOptions:
  disableNameSuffixHash: true
