apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authentik
resources:
  - namespace.yaml
  - helm-repository.yaml
  - secrets.enc.yaml
  - helm-release.yaml
  - http-route.yaml

configMapGenerator:
  - name: authentik-values
    files:
      - values.yaml

generatorOptions:
  disableNameSuffixHash: true
