apiVersion: v1
kind: Secret
metadata:
    name: authentik-values-secret
    namespace: authentik
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:7pDNYLFWpJ6oeFtyA6r2Ovd9+gN5HORHFptaev1SaGUKFn1GWV5tj22gzFDezlfDP/YcmCXROyvAf4NX91IhUcqQWZSPRUMlH8DTuNprl7JbqNawlE8JDdwNqsx8siX7tRpXunESpdE78zNKkeB/Fhw=,iv:MyQdD9Kromu8rSMalCYkVDkuNrLeQ335BfyD4czzfdA=,tag:UJJmwnwI2RU0C5hW8BLcTQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCckM1czBicTRvb3gvNDlZ
            eGkrT1BXMWN1eDFLeFNrMlZyN2lYQ2UrSXdVCnZ4dWl3U2VydnA2YUhNQk9BRURj
            c2hxVHVjOEVYQUlYVFg4UC8xMUhIUUkKLS0tIGxlY2N1bFFxLzRBRjViOHJiWHFG
            MlJlMzExWmtsemFIc2dXQjBJcHhISUEKi3x+ImrP1Y1QPm+GxGuUGRgqQ4KhFBTE
            vbMDUXtqfz2oCUsul4MQ1V5fMpIw0WHNPOgyOpaDOCjFCKEfl4f/+A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kyhazfmr49eddkxfws9apdlauaevqsktfhfhyxdhkxhwdg03qszs7c337j
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-28T12:56:27Z"
    mac: ENC[AES256_GCM,data:T3p/0XAsMQhKQQFLdh9GRR2F/HC1cCyVkA7wC4ebSUsdSjgew6Sgui1s2/mwJpbK2lE1gZ8s9QJgCutyBEbevzGKDUSIOzy5elzcllr8CVXCgsOoixd1Ys3CfdjY+Szlw83Nh15AxOWIoK+b3r8xupZEaA1BTM1vpbIUODm3wko=,iv:e45A9D5/gdQRlG2Jr2JyRa/ezfpTnHbheI1E/IosQpU=,tag:3QIc6WCA84cIK6CJ22GRJQ==,type:str]
    version: 3.13.2
