apiVersion: v1
kind: Secret
metadata:
    name: authentik-config
    namespace: authentik
type: Opaque
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:48/5oT4v3Yy1U1nFvrlxsmMMUsKAFQ7QZX/Xu6zVyWRgfXtXj1oYe3h76aIrye/9ygP+rb91LEYm9LEu8kBF+g==,iv:7PfdC4oY+4+ILLuEBKddVFCMRqkpZrB/34+OZjH8dqo=,tag:w8Ih7r/k+LtQzSqUmAq8zg==,type:str]
    AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:c/PVKoVrZkJuhmGPOBbAkXZebKRkXevezRvTwISk2ww=,iv:mnxEEfzSn6bXdxO6FlJUbFtzeWG7bi0rs8KKXe+qcQ0=,tag:2TgpW0IO4RlJGGyhtMjWeg==,type:str]
    AUTHENTIK_POSTGRESQL__HOST: ENC[AES256_GCM,data:TsFKTAPTuHK73XodIuYjxnj8Hqo=,iv:mIQC3HGS4rGr20AP4RYCqXHidAfqhVHOVIIEkVarKBk=,tag:4q3Gju+22w8vwhexEvtwTA==,type:str]
    AUTHENTIK_POSTGRESQL__PORT: ENC[AES256_GCM,data:wk9gvA==,iv:rMfraRmJ5SZ78WssqRTNYrzsDN2SIaam3YbZfBFRaiE=,tag:/2GXOLqTHvVHNBMNlfda9Q==,type:str]
    AUTHENTIK_POSTGRESQL__NAME: ENC[AES256_GCM,data:ZnT3ZQm+1atD,iv:t0+AubXtzZOmFMhHsZi8O1ZUClk7P9Tfexwahvo9STc=,tag:hokCfXDnYRwyUv3l6cKamg==,type:str]
    AUTHENTIK_POSTGRESQL__USER: ENC[AES256_GCM,data:P+TDIbpKnkd7,iv:J4hc13JjWN968vKE71CqJn0QpKxFQjzkmW7C4Yrwz0w=,tag:sKtDbdJon9okwDXKEBrWWw==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:6+Gg9EZdFy1vZy0r1fKhCNfZ36NPFnwumfcms8kHynkm2TQowSW61Q==,iv:0JTazOu95CvWkpu0Efh2ulocgSD273EADWIT6bBzXII=,tag:LSKtC1XNfLgoGmUJRp5iAQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSTlk5aDI2ODgzZGlvek03
            a1VsUzZqQ3AwTmR3SXhINStWWTNtWkp6N2pnCk8rbXV1bExMam9QcHhESG9UVksr
            cGJHcG9QSlI3YVkrZWdzNnBxKzdRMmcKLS0tIE1sekZrTTVZbSt1YVU4YitxeVlK
            cnNBcFErVHYrVk0xYkNqREMxYjdGUFkKH9pQ2LV1b5f0h+RtIk6N93dTkqu5/yh8
            3Emn7uu6vTGMxYVyyVGiReoXriwbsnNTebap9fV+V/tYNJXiyT0FbA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kyhazfmr49eddkxfws9apdlauaevqsktfhfhyxdhkxhwdg03qszs7c337j
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-28T13:05:30Z"
    mac: ENC[AES256_GCM,data:Pq0plzWhYLnP1SpG1IuQWchwcNqU+Lqx96NF4jL92PU2kYQhnJ3C+FHiirjMsYJOc9/NMTpe0kqiSq/PHw3+haAYDYaCi0so12jlqKKsZFQc5pWsLhaj9ROh0v3pgUG98xjcioVITkwBpxyjXaX+drsaiOkor1GP7knANdRB6G4=,iv:goq7UFjtFNgZIN3iXB7KDFUM0rmQR1tqkqgC1DRjyX8=,tag:SJ55wvfGEwvUu7VMS+TWpw==,type:str]
    version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
    name: authentik-postgresql-credentials
    namespace: authentik
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:+d41KyEvyhm+uV/l+GpsXmcDUXpqBKQ91aG6ubKlRjSTEcM+FjvwAw==,iv:PF0RvIkkBQE83IgwsfWP0Z6tHX6MMgqgQbd2y5eNzrI=,tag:X7ItyD7naSj0roku5SLlGg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSTlk5aDI2ODgzZGlvek03
            a1VsUzZqQ3AwTmR3SXhINStWWTNtWkp6N2pnCk8rbXV1bExMam9QcHhESG9UVksr
            cGJHcG9QSlI3YVkrZWdzNnBxKzdRMmcKLS0tIE1sekZrTTVZbSt1YVU4YitxeVlK
            cnNBcFErVHYrVk0xYkNqREMxYjdGUFkKH9pQ2LV1b5f0h+RtIk6N93dTkqu5/yh8
            3Emn7uu6vTGMxYVyyVGiReoXriwbsnNTebap9fV+V/tYNJXiyT0FbA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kyhazfmr49eddkxfws9apdlauaevqsktfhfhyxdhkxhwdg03qszs7c337j
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-28T13:05:30Z"
    mac: ENC[AES256_GCM,data:Pq0plzWhYLnP1SpG1IuQWchwcNqU+Lqx96NF4jL92PU2kYQhnJ3C+FHiirjMsYJOc9/NMTpe0kqiSq/PHw3+haAYDYaCi0so12jlqKKsZFQc5pWsLhaj9ROh0v3pgUG98xjcioVITkwBpxyjXaX+drsaiOkor1GP7knANdRB6G4=,iv:goq7UFjtFNgZIN3iXB7KDFUM0rmQR1tqkqgC1DRjyX8=,tag:SJ55wvfGEwvUu7VMS+TWpw==,type:str]
    version: 3.13.2
