apiVersion: v1
kind: Secret
metadata:
    name: authentik-config
    namespace: authentik
type: Opaque
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:7uNYy2Eexb7JnqPy8uyzPS2kzaCGo7WVQ6RBjZ1rt+sGBfD3056P30hs1BvK11RKOV9llhYnXkHZkW65RxAT5A==,iv:lqNee+kb4JVi+XoTKmWpN+kGIgJ+koJyYDX1AXuNVUE=,tag:u6LT7NTxl4+a1h7AOmDBIg==,type:str]
    AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:pIJv7f0phpgcxmXGzTdWPrfSAeGFLr5xOttvLiVWNFA=,iv:f0suJPZ4cuVV2XQQhtcv9RLFPFC1961gXZlfsSpOtIU=,tag:GZkiGBdRZByblIQg0zADMA==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:Ygyff0EpMSpTzS7EDM0KAJTqmiFnt1Tk2YiTbBCfXyoFpnWG36jFog==,iv:OK7sz2E7hv8TqLlt/S4LmpJVtIYejK5vq+5c6qM1oT0=,tag:JilW2gThC1J2GhSortXjRg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvMGZRTDd4cXI0TWpBWUpm
            Um1wRisvV0FwRVd5dm5kaFUwSVJ1TmJlQ3dFCmJGZVpaRDBGRUw0b0o1djQwcWlG
            M3BvalJXazRxQzZyNCtWOWNaQXlxVTQKLS0tIForOTlMRXBFUEVRd28xRzFoR1dn
            MExhNjBTbW5LSzIwcVMxT25DV2dZa2sK4BQqURLcLveCZM4z2re8LnkQGJSoJ6aj
            xPbJfkbXkmecCavWV43EU/hSROqDYWsH30t79wDEdWM5S0h28bn+zA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kyhazfmr49eddkxfws9apdlauaevqsktfhfhyxdhkxhwdg03qszs7c337j
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-28T13:01:32Z"
    mac: ENC[AES256_GCM,data:3ne6O1dkTa2HxnOdspknp2lEituI5rb6T+69QWUONwwq1As62g1knaDPqxHZGHD3xaFnMdf/Fl5CQRU+pMxSugf7RiC568ZJh9MiKKp4tWyyMk4kP6tvZZkrjLogkRYSkAG3yJ8Lr73AuvEgpU9MCeB9KxXIjMvYwyL5+oKaQXo=,iv:DfElQWeTgrU/JDdzCQoIIy2kET0ZHZ0zzneZ0R7KB4c=,tag:WFaXRnL80Ao9JS1Y16pC/w==,type:str]
    version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
    name: authentik-postgresql-credentials
    namespace: authentik
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:Ak3fYUGvHoj2QsY4uNQTGZ6jMYUSTeIz462zzLm4cShTbt2GXA+KDQ==,iv:A0fbJZjsfs4CWPUO96Szq02S8E+Ou5vwLam4+OwDymg=,tag:AV0GQXkTSnQXTwqn41vtDQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvMGZRTDd4cXI0TWpBWUpm
            Um1wRisvV0FwRVd5dm5kaFUwSVJ1TmJlQ3dFCmJGZVpaRDBGRUw0b0o1djQwcWlG
            M3BvalJXazRxQzZyNCtWOWNaQXlxVTQKLS0tIForOTlMRXBFUEVRd28xRzFoR1dn
            MExhNjBTbW5LSzIwcVMxT25DV2dZa2sK4BQqURLcLveCZM4z2re8LnkQGJSoJ6aj
            xPbJfkbXkmecCavWV43EU/hSROqDYWsH30t79wDEdWM5S0h28bn+zA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kyhazfmr49eddkxfws9apdlauaevqsktfhfhyxdhkxhwdg03qszs7c337j
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-28T13:01:32Z"
    mac: ENC[AES256_GCM,data:3ne6O1dkTa2HxnOdspknp2lEituI5rb6T+69QWUONwwq1As62g1knaDPqxHZGHD3xaFnMdf/Fl5CQRU+pMxSugf7RiC568ZJh9MiKKp4tWyyMk4kP6tvZZkrjLogkRYSkAG3yJ8Lr73AuvEgpU9MCeB9KxXIjMvYwyL5+oKaQXo=,iv:DfElQWeTgrU/JDdzCQoIIy2kET0ZHZ0zzneZ0R7KB4c=,tag:WFaXRnL80Ao9JS1Y16pC/w==,type:str]
    version: 3.13.2
