authentik:
  existingSecret:
    secretName: authentik-config
  error_reporting:
    enabled: false

server:
  replicas: 1
  podAnnotations:
    checksum/authentik-config: "ab5008401c8012426db8f800e8457a5529d233f2d02f41286e71d5a5547a418a"
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      memory: 1Gi

worker:
  replicas: 1
  podAnnotations:
    checksum/authentik-config: "ab5008401c8012426db8f800e8457a5529d233f2d02f41286e71d5a5547a418a"
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      memory: 1Gi

postgresql:
  enabled: true
  auth:
    existingSecret: authentik-postgresql-credentials
    secretKeys:
      userPasswordKey: password
  primary:
    persistence:
      enabled: true
      size: 10Gi
