apiVersion: v1
kind: Service
metadata:
  name: stalwart
  namespace: mail
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: stalwart
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP