apiVersion: v1
kind: PersistentVolume
metadata:
  name: strapi-pv
  labels:
    app: strapi
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard 
  persistentVolumeReclaimPolicy: Retain 
  hostPath: 
    path: /strapi-data
    type: DirectoryOrCreate
