apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: strapi-pvc
  namespace: portfolio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
