apiVersion: v1
kind: Service
metadata:
  name: postgres-headless
  namespace: immich
spec:
  clusterIP: None
  selector:
    app: immich-db
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
      protocol: TCP
