apiVersion: v1
kind: Secret
metadata:
    name: immich-db-secret
    namespace: immich
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:NMLx8Z/Xc58rPZbOZcsRpMJVDiqZLKF16RqTyypXBKfP3kTbmava8nGsNE2scV5Rle678pcm5ICXMsVgNB2O1Q==,iv:wPUgimbPBLYEmzM+A2AK6u/gVsPg7gymYwf3b4q5/jk=,tag:QVdJco9t6XrjA6MiJ/PhTw==,type:str]
sops:
    age:
        - recipient: age1kyhazfmr49eddkxfws9apdlauaevqsktfhfhyxdhkxhwdg03qszs7c337j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUaFNJMmZqaHUwSElSWUhO
            NGt5V0FnNnpCSU1YMjZ4TVYwUEUwVzUxVmdvCnh4dDgwMmhkdWlBLzhrR2t5eUgr
            aEFzcmdaSVdQdnRocnN0MTRldkdveTAKLS0tIEJUZDMzYzlkN2VtQWh3aUJMYUht
            TjBqOTk4MXZtNlNBdXczWUI5SFJ3M0UKhVA9nRcQLq0SkZ9RRRIuQSKlTifTG+AI
            lg/S9GaysWkpgWIPMkmeyVU+m8SsYJKeU/UXLGwMzsQRoTzm8dcpVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-11T17:10:50Z"
    mac: ENC[AES256_GCM,data:qXmThxvN9X9+S47YTID7P4jVgnVWpTQZ+8TX/lGOrvVhimyPFRZ1gCT2aFnSJuS6KAftAr9nWH5O+f4Chrm8/H+b+gftnPyJnRkb2Z0rf76Y3VDX2FpAo6Pg3e7P2ITltPw4njrVF4RL4wjzVFAA88J3avG5KPaYUB5QoZtKmrk=,iv:2kEcGl0fYgRBJN92bMK5o/dCHfWbYsw2gRTyTnsYKPo=,tag:R1t5wNDVKyPbQnUbn+uHiw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
