apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  # PostgreSQL
  - postgres/secrets.enc.yaml
  - postgres/config-map.yaml
  - postgres/deployment.yaml
  - postgres/pvc.yaml
  - postgres/service.yaml
  - postgres/backup-pvc.yaml
  - postgres/backup-cron-job.yaml

  # Redis
  - redis/deployment.yaml
  - redis/service.yaml

  # Machine Learning
  - machine-learning/deployment.yaml
  - machine-learning/pvc.yaml
  - machine-learning/service.yaml

  # Main server Immich
  - server/config-map.yaml
  - server/deployment.yaml
  - server/pvc.yaml
  - server/service.yaml
  - server/http-routes.yaml
