apiVersion: v1
kind: ConfigMap
metadata:
  name: minecraft-whitelist
  namespace: minecraft
data:
  whitelist.json: |+
    [
      {
        "uuid": "44fb2549-ad23-408d-af5e-d92d01fbcc23",
        "name": "Volgare"
      }
    ]

