# This file contains all properties used my the Minecraft server
apiVersion: v1
kind: ConfigMap
metadata:
  name: minecraft-server-config
  namespace: minecraft
data:
  VERSION: 1.21.11
  EULA: "TRUE"
  TYPE: "PAPER"
  ENABLE_RCON: "TRUE"
  BROADCAST_RCON_TO_OPS: "TRUE"
  DIFFICULTY: "normal"
  MODE: "creative"
  MOTD: "Bienvenue sur mon serveur Minecraft!"
  MAX_PLAYERS: "5"
  ONLINE_MODE: "TRUE"
  FORCE_GAMEMODE: "TRUE"
  ENABLE_WHITELIST: "TRUE"
  WHITELIST: "Volgare"
  PLUGINS: |
    https://cdn.modrinth.com/data/1u6JkXh5/versions/p8T2aZ8U/worldedit-bukkit-7.4.2.jar
    https://download.luckperms.net/1631/bukkit/loader/LuckPerms-Bukkit-5.5.42.jar
    https://cdn.modrinth.com/data/DKY9btbd/versions/EZl3moba/worldguard-bukkit-7.0.16.jar
