# This file contains all properties used my the Minecraft server
apiVersion: v1
kind: ConfigMap
metadata:
  name: minecraft-server-config
  namespace: minecraft
data:
  VERSION: 26.1.2
  EULA: "TRUE"
  TYPE: "PAPER"
  MEMORY: "2G"
  ENABLE_RCON: "TRUE"
  BROADCAST_RCON_TO_OPS: "TRUE"
  DIFFICULTY: "normal"
  MODE: "creative"
  MOTD: "Bienvenue sur mon serveur Minecraft!"
  MAX_PLAYERS: "5"
  ONLINE_MODE: "TRUE"
  FORCE_GAMEMODE: "TRUE"
  ENABLE_WHITELIST: "TRUE"
  WHITELIST: "Volgare"
  MODRINTH_PROJECTS: |
    worldedit
    luckperms
    worldguard
