apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: postgres-sonarqube
  namespace: sonarqube
spec:
  type: oci
  interval: 1h
  url: oci://registry-1.docker.io/bitnamicharts
