apiVersion: v1
stringData:
    #ENC[AES256_GCM,data:kRASvsN3owTR1X/OlFSgbBoAuyoDNjLVFfA/Upa97YT/wGiuRD7KHG+b,iv:pCPNwPrbvX96mCGLFSjaWjNUpH6bL7Xun5FucFOpLdA=,tag:5craq/hAeKry/07jwxdC0w==,type:comment]
    postgres-password: ENC[AES256_GCM,data:pAzGAR4v8BOvkUifnO1fMNIyilM23loNjDH40vBUcSExXESex6BR+QNJj/O0arnf9HowmQ==,iv:A1gwOLtl4yQqFAvs9XuO9ET3Xo6vzwoQbe8aEEIM0b0=,tag:hrvfvki6AMfXRt3W4npHeQ==,type:str]
    #ENC[AES256_GCM,data:Clxhs1w26B7Lta4iAeVYX8eI/NsxL/GQpSSq,iv:JR3gSKFtxTGhYtcLWdDDBeTp/XWKWVPQWGoJNtqou4g=,tag:Ku0MXviY/2Pq9DPbBwQcEg==,type:comment]
    password: ENC[AES256_GCM,data:PrUAlhVlv2hrQ+1xoe1yDVIX+eXEoRJAW8JomWrTTr5bCiUqSQ0vjYk3BphEyV8odhL3QA==,iv:nGE1QCaEeIEKEa5GWVFqDQL0oDIHxGUA+RsTytEsKBc=,tag:R53IP5qwfRj52z/g+qF3ow==,type:str]
kind: Secret
metadata:
    name: sonarqube-postgres-secret
    namespace: sonarqube
sops:
    age:
        - recipient: age1kyhazfmr49eddkxfws9apdlauaevqsktfhfhyxdhkxhwdg03qszs7c337j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3RUF4MjB2Q2tYckdEbkNU
            ZEYwTXpwOXgyYWZ1ekJtNFd4ZjBTY3ZUOEJvCi9DREkyOEZaak1kMHFKWmVmNm5V
            MjNyaUx1ZWxzdUt4NFBEQlRyMC9oaUkKLS0tIHRiT0NVRlY3enEwWXRabUNsOUt3
            UU5JU0ozbjRxTnVReDRCOFZ0MVJEc3cKcl6RV7T5yORE/sHugtZ7rtTRI0XbEHhU
            GFBKlvLSv0Z8bK3rQyBZN3Hp4nvsy6satSQjkK5tbkt/qrq0lMdz8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-11T17:10:50Z"
    mac: ENC[AES256_GCM,data:LNylQSnUMZNIijaF1CEgZ4CTGs80AU5MEJb0r6i0vMVXH3uRb70pSBcNiwB/BuC5SyThI62nF5sISUGu/Dw8ueS4VVR6axDDqHE9YBOuG90HVmsm5o1hZ8WPP0dI1uPkdOi68QHl/13daqjRK7JRxyuus9zjN68xz9M+hR5FqWQ=,iv:7aHTWFnH9A6V+1UucubzNJkA2+JlA9F9BQgtn9Tmyqw=,tag:LDvUalrBBQyQgbfTXgJqXQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
