apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-postgres-strapi-pvc
  namespace: portfolio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-path
