apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tor-hostname-data
  namespace: envoy-gateway-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
