apiVersion: batch/v1
kind: CronJob
metadata:
  name: mongodb-backup
  namespace: portfolio
spec:
  schedule: "0 2 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backup-tool
              image: mongo:latest
              command:
                - /bin/sh
                - -c
                - |
                  echo "--- Starting backup process ---"
                  DATE=$(date +%Y-%m-%d_%H-%M-%S)
                  BACKUP_NAME="mongo-backup-$DATE.gz"

                  # 1. Dump and compression on the fly
                  # --archive outputs a single file, --gzip compresses it
                  mongodump --uri="mongodb://$MONGO_USERNAME:$MONGO_PASSWORD@$MONGO_ADDRESS:$MONGO_PORT/$MONGO_DATABASE" --archive=/backup/$BACKUP_NAME --gzip

                  if [ $? -eq 0 ]; then
                    echo "Success: Backup created: $BACKUP_NAME"
                  else
                    echo "Error: mongodump failed"
                    exit 1
                  fi

                  # 2. Retention policy: Delete files older than 7 days
                  echo "--- Cleaning up old backups ---"
                  find /backup -name "mongo-backup-*" -mtime +7 -delete
              env:
                - name: MONGO_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: backend
                      key: NODE_JS_MONGODB_USERNAME
                - name: MONGO_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: backend
                      key: NODE_JS_MONGODB_PASSWORD
                - name: MONGO_PORT
                  valueFrom:
                    configMapKeyRef:
                      name: backend
                      key: NODE_JS_MONGODB_PORT
                - name: MONGO_ADDRESS
                  valueFrom:
                    configMapKeyRef:
                      name: backend
                      key: NODE_JS_MONGODB_ADDRESS
                - name: MONGO_DATABASE
                  valueFrom:
                    configMapKeyRef:
                      name: backend
                      key: NODE_JS_MONGODB_DATABASE
              volumeMounts:
                - name: backup-storage
                  mountPath: /backup
          restartPolicy: OnFailure
          volumes:
            - name: backup-storage
              persistentVolumeClaim:
                claimName: mongodb-backup-pvc
