apiVersion: v1
kind: PersistentVolume
metadata:
  name: server-immich-pv
  labels:
    app: immich
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /immich-storage
    type: DirectoryOrCreate
