apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: server-immich-pvc
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: local-path
