apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: portfolio
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: yaniskouidri/portfolio-backend:0.1.0-arm
        ports:
        - containerPort: 3001
        env:
        - name: MONGODB_USERNAME
          valueFrom:
            secretKeyRef:
              name: portfolio-secrets
              key: MONGODB_USERNAME
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: portfolio-secrets
              key: MONGODB_PASSWORD
        - name: MONGODB_ADDRESS
          value: mongodb
        - name: MONGODB_PORT
          value: "27017"
        - name: MONGODB_DATABASE
          value: mydb?authSource=admin
        - name: FRONTEND_URL
          value: https://beta.kouidri.fr # my domaine (ex: http://portfolio.kouidri.fr)
        - name: NODE_ENV
          value: production
        - name: PORT
          value: "3001"
        - name: SIGN_UP_KEY
          valueFrom:
            secretKeyRef:
              name: portfolio-secrets
              key: SIGN_UP_KEY
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: portfolio-secrets
              key: JWT_SECRET
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "1"
            memory: "512Mi"
