apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: portfolio-frontend
  name: portfolio-frontend
  namespace: portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-frontend
  strategy: {}
  template:
    metadata:
      labels:
        app: portfolio-frontend
    spec:
      containers:
      - image: yaniskouidri/portfolio-frontend:0.1.5-arm
        name: portfolio-frontend
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "500m"
            memory: "1Gi"
