apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: portfolio-frontend
  name: portfolio-frontend
  namespace: portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-frontend
  strategy: {}
  template:
    metadata:
      labels:
        app: portfolio-frontend
    spec:
      containers:
      - image: yaniskouidri/portfolio-frontend:0.1.6-arm
        name: portfolio-frontend
        imagePullPolicy: Always
        env:
        - name: ASSET_DIR
          value: /usr/share/nginx/html
        - name: APP_PREFIX
          value: PREFIX_
        - name: PREFIX_BACKEND_URL
          value: "http://localhost:3001"
        - name: PREFIX_DOCS_ROUTE
          value: "/data/docs"
        resources:
          limits:
            cpu: "500m"
            memory: "1Gi"
