apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - authentik
  - crowdsec
  - immich
  - minecraft-server
  - n8n
  - personal-website-v2
  - sonarqube
  - wireguard-vpn
  - mail