apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - crowdsec
  - immich
  - minecraft-server
  - n8n
  # - personal-website
  - personal-website-v2
  - sonarqube
  - wireguard-vpn