apiVersion: v1
kind: Service
metadata:
  name: bulwark
  namespace: mail
  labels:
    app.kubernetes.io/name: bulwark
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: bulwark
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
