apiVersion: batch/v1
kind: CronJob
metadata:
  name: immich-db-backup
  namespace: immich
spec:
  schedule: "0 2 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: postgres-backup
              image: postgres:16-alpine
              command:
                - /bin/sh
                - -c
                - |
                  echo "Début du backup..."
                  # La date pour nommer le fichier
                  DATE=$(date +%Y-%m-%d_%H-%M-%S)
                  # La commande pg_dump
                  # PGPASSWORD est utilisé pour éviter le prompt interactif
                  PGPASSWORD=$POSTGRES_PASSWORD pg_dump -h postgres -U postgres -d immich > /backups/immich_db_$DATE.sql

                  # Nettoyage optionnel : supprimer les fichiers de plus de 7 jours
                  find /backups -type f -mtime +7 -name "*.sql" -delete
                  echo "Backup terminé : /backups/immich_db_$DATE.sql"
              env:
                # Récupère les secrets de ta base de données existante
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: immich-db-secret
                      key: POSTGRES_PASSWORD
              volumeMounts:
                - name: backup-storage
                  mountPath: /backups
          restartPolicy: OnFailure
          volumes:
            - name: backup-storage
              persistentVolumeClaim:
                claimName: backup-immich-pvc
