apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-immich-pvc
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
