apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-immich-db
  namespace: immich
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-db
  template:
    metadata:
      labels:
        app: immich-db
    spec:
      containers:
        - name: postgres
          image: ghcr.io/immich-app/postgres:18-vectorchord0.5.3-pgvector0.8.1
          envFrom:
            - secretRef:
                name: immich-db-secret
            - configMapRef:
                name: immich-db-config
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1"
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-immich-pvc
