apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-immich-pv
  labels:
    app: immich
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard 
  persistentVolumeReclaimPolicy: Retain 
  hostPath: 
    path: /immich-db
    type: DirectoryOrCreate
