apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-immich-pvc
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard
