apiVersion: ENC[AES256_GCM,data:p7k=,iv:rB+iyOudvguJKeVo4FmfwmQds9NSl+RX4jXVRz1a9VY=,tag:4sjFMRroi8oGpvjclTrj1w==,type:str]
kind: ENC[AES256_GCM,data:6Gyikfvn,iv:vcdQRa9IrcG1yQcljw1kNL6ilfFNGPsRbuoAm5WsLQ0=,tag:O/X2C+i4zisKhG6wYf9VEg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:wg0eAFXzHDGNVN+BXjVvuA==,iv:fuKBb8J1fGyzV7B7Lp5Jvd75k80fKJTkPKlWWXnBWmw=,tag:EHHkFlIPJ2/Gsz20N1JkQg==,type:str]
    namespace: ENC[AES256_GCM,data:r6MVLhpW,iv:GQhuefYrC9TOSxo27XMoViyBde5lw1gDJz6rtF4qGzQ=,tag:nIkWAuAXvlqqTfyxcWZuyA==,type:str]
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:kdgZJt1fJbRhkGgXx7Fqhmd+D9M8pVyWU9DT0sR1IsbtFTKyjfAE8n8ZJNQbNwxV3tLHeH6ErbZiOre+Q4JGqQ==,iv:Mpan8VeIvSmJmyE0ImQyemnEtOEV+ArmvqVT8vOfXU4=,tag:rJU/xbsegTLOhFawMSQ0IQ==,type:str]
sops:
    age:
        - recipient: age1kyhazfmr49eddkxfws9apdlauaevqsktfhfhyxdhkxhwdg03qszs7c337j
          enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4UG9MNVVXTUxRekpqcVVv
              bU1MNGFLQmxGVGc3VEJ2akY3TnI0SjZDVDNnCnJOb3owM0pDUGhDeWx2ZFM5bzlE
              QkJkbndEcHgySWtVbFgzTkxGRDhCa28KLS0tIEVyS0EzUXhLSWpPeERpemJ1aTBt
              d01XTWtySUU0aDU5RzZDR2srRSs3b0UKTXyTrRJeq49cZ0Pos1/1EHto1QFijMzu
              App+vZoxYeib33f0GXnrQwk0vv8EdLm/EKHa1ZIYV/6ZR4nER6o1rw==
              -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-21T18:23:22Z"
    mac: ENC[AES256_GCM,data:9jIyIiF5/nLatObukbmnVhKGASNwc2cPny8Qb+RI4M+lqoL0w4pqVYz/InpyZr1cvWWEO27CaybcEED4nfVqKB4zcVvcYTCUIoxbNoXbEr7jg7PFRjll7UodcOSZMuY7eA9xd7yv9blxXSqy6qiUf/8apALW/o6eEKbBlGOPwKk=,iv:Wh5Kj9cR5mV1vejzm/D3+kzUgjgq9pmQP3XBfr1nsic=,tag:MCIsqy+vYIKjkjeskL++3A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
