apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kouidri-fr-tls
  namespace: envoy-gateway-system
spec:
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "mail"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "mail"
  secretName: kouidri-fr-tls
  issuerRef:
    name: letsencrypt-prod
    # name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: kouidri.fr
  dnsNames:
    - kouidri.fr
    - www.kouidri.fr
    - photos.kouidri.fr
    - sonarqube.kouidri.fr
    - n8n.kouidri.fr
    - mail.kouidri.fr
    - webmail.kouidri.fr
    - kouidri.me
  privateKey:
    algorithm: ECDSA
    size: 384
