apiVersion: ENC[AES256_GCM,data:AbM=,iv:sYpTwb2o9Wo3qk4TFTqukuqon/NinoTMKe+sMBMqjhQ=,tag:S9lpbqIeI5nmpA2vo8kqGg==,type:str]
kind: ENC[AES256_GCM,data:YuwAjK3r,iv:l1Q2io657wnTx646v/pcqADHtp8bw7d03P3lfNWntOg=,tag:6wtzMy3S2CQDqpUQs9B7Sg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:9hq0r/VkL1tybIS0iL7w,iv:Yhy0byHurGzaVGqyfYpb+eB7kEsIb6tNdGr76QZdrRw=,tag:aUc1vsx/gZj4W1vymGVRJQ==,type:str]
    namespace: ENC[AES256_GCM,data:phjjScLF4D0=,iv:FSAUPcyKfCeKiDcMha4kndQ5t7+Q8PL1oJ7tT5T57jY=,tag:0p4eH01i/ZlR2UTf/aLWWQ==,type:str]
type: ENC[AES256_GCM,data:z+9+G26f,iv:WdPzfUnbCo5mBY2hAb538IacDh8ImPjWkhzrLC8CyI0=,tag:a1CD674Bjepld5T3mstVKw==,type:str]
stringData:
    ENROLL_KEY: ENC[AES256_GCM,data:aWuzHJeTj8hiYUfvzHJRIJIeVWoo04Ttkg==,iv:NN3NteZFmYXZDZFlNoL327s6fv6ynWvIDVfAM5RZtWo=,tag:jD5kb3c8Xyfw+ofhWiSwYQ==,type:str]
    ENROLL_INSTANCE_NAME: ENC[AES256_GCM,data:laC+oKrl02Wjd2cb9UKY,iv:i+u386fOyOSCk+tytjL5jxlczsRm2axApLRz8u8UU+0=,tag:WHnZ+42T/B/EvVFZve/HaA==,type:str]
    ENROLL_TAGS: ENC[AES256_GCM,data:oVg8/67Qkm9QDH5ruLTWB0g=,iv:eL8lbXcF6nf4LF6plXiVIrpZwY3X+ueLL7seKDcP50Y=,tag:7zowu1iR7bL9yHeDOOCW5g==,type:str]
sops:
    age:
        - recipient: age1kyhazfmr49eddkxfws9apdlauaevqsktfhfhyxdhkxhwdg03qszs7c337j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWQ0RXM1k1Y0x1dWR2UUtx
            dXVvTk54Y2pXMzkwOHBJM2hhUVZSNmJvNWhrCkM3VC9CRTNqK0lJbWdXSFM4RTBZ
            aVBSakNLWml5RUhmbHpmZmRwTU5sVkEKLS0tIDExWC83UUpQaDBveWliQStzdmRU
            VllZT2NWYmtGMHY4UnFaU0o1N1RsWVkKkXJyX19Q/iU2utE4+16z0aUEONbHkTm1
            6H7qkGfiav3SpwcHrdg/as9NR7bspmJehoD/rxYSTmuaaHrwTTACrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-21T08:14:52Z"
    mac: ENC[AES256_GCM,data:gsupkW61y/vXztGqDuilSA0NtrJ3Dj7EqpCBv4Zj5GVEFaL95XFC+RPfaDr89JQRWM+5T3NhaygaDJrC5jKwkctHXCuE0F2/Ni+lElqQ994qVisRFWAcdSkBOSkoRRtPP0prbLiA0d+qmcVeoG/fL7GKKXdtQz5P0mK2OzocKoQ=,iv:CA+pjjWvIGoliyb6BwDHsfmAqh5fknDTfIzKrNJ7Mc4=,tag:Ao5DmD+mdIE4EnKnOhID+g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
